# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: carthage update --platform iOS
  env:
    GITHUB_ACCESS_TOKEN: aa2f6ea087600c775ebedc5f70950fed300b3231
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'GithubUser'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
