shared:
  image: ruby:2

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
        - bundle_install: bundle install
        - export LC_ALL=en_US.UTF-8
        - export LANG=en_US.UTF-8
        - bundle exec fastlane tests
