# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Description of what the lane does"
	lane :custom_lane do
	# add actions here: https://docs.fastlane.tools/actions
	end

	desc "Build the beta application"
	lane :beta do
		build_app(scheme: "GithubUser")
	end

	desc "Run test"
	lane :tests do
	run_tests(project: "GithubUser.xcodeproj",
            scheme: 'GithubUser',
			devices: ["iPhone 8"],
			code_coverage: true,
			result_bundle: true,
			fail_build: false)
	end
end
